#server:
#  port: 8007

spring:
  application:
    name: service-order

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/taxi_order?characterEncoding=utf-8&serverTimezone=GMT%2B8
    username: username
    password: password

mybatis:
  mapper-locations: classpath:/mapper*/*.xml

#logging:
#  level:
#    ltd.erato.taxi.service.order.dao: debug

---
spring:
  profiles: 8007
server:
  port: 8007
---
spring:
  profiles: 8017
server:
  port: 8017